#!/bin/csh

echo ""
GCM_SIV_1_KEY_ENC 0  0
echo ""
GCM_SIV_1_KEY_ENC 0  8
echo ""
GCM_SIV_1_KEY_ENC 0  12
echo ""
GCM_SIV_1_KEY_ENC 0  16
echo ""
GCM_SIV_1_KEY_ENC 0  32
echo ""
GCM_SIV_1_KEY_ENC 0  48
echo ""
GCM_SIV_1_KEY_ENC 0  64
echo ""
GCM_SIV_1_KEY_ENC 1  8
echo ""
GCM_SIV_1_KEY_ENC 1  12
echo ""
GCM_SIV_1_KEY_ENC 1  16
echo ""
GCM_SIV_1_KEY_ENC 1  32
echo ""
GCM_SIV_1_KEY_ENC 1  48
echo ""
GCM_SIV_1_KEY_ENC 1  64
echo ""
GCM_SIV_1_KEY_ENC 12  4
echo ""
GCM_SIV_1_KEY_ENC 18  20
echo ""
GCM_SIV_1_KEY_ENC 20  18
echo ""
GCM_SIV_1_KEY_DEC 0  0
echo ""
GCM_SIV_1_KEY_DEC 0  8
echo ""
GCM_SIV_1_KEY_DEC 0  12
echo ""
GCM_SIV_1_KEY_DEC 0  16
echo ""
GCM_SIV_1_KEY_DEC 0  32
echo ""
GCM_SIV_1_KEY_DEC 0  48
echo ""
GCM_SIV_1_KEY_DEC 0  64
echo ""
GCM_SIV_1_KEY_DEC 1  8
echo ""
GCM_SIV_1_KEY_DEC 1  12
echo ""
GCM_SIV_1_KEY_DEC 1  16
echo ""
GCM_SIV_1_KEY_DEC 1  32
echo ""
GCM_SIV_1_KEY_DEC 1  48
echo ""
GCM_SIV_1_KEY_DEC 1  64
echo ""
GCM_SIV_1_KEY_DEC 12  4
echo ""
GCM_SIV_1_KEY_DEC 18  20
echo ""
GCM_SIV_1_KEY_DEC 20  18
